openapi: 3.0.0
info:
  title: Sonic API
  version: 1.0.0
  description: API sobre los personajes de Sonic
servers:
  - url: http://localhost:8080
components:
  schemas:
    Character:
      required:
        - nombre
        - genero
        - habilidad
        - alineacion
      type: object
      properties:
        nombre:
          type: string
          example: Shadow
        genero:
          type: char
          example: M
        habilidad:
          type: string
          example: Speed
        alineacion:
          type: string
          example: Dark
paths:
  /characters/{id}:
    get:
      summary: obtiene una lista de personajes
      tags:
        - Characters
      responses:
        '200':
          description: lista de personajes
        '404':
          description: not found
        '500':
          description: connection error
    post:
      summary: agrega un personaje
      description: agregar un personaje nuevo
      requestBody:
        description: agregar un personaje de sanic nuevo
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Characters"
      tags:
        - Characters
      responses:
        '200':
          description: lista de personajes
    get:
      summary: obtiene una lista de personajes
      tags:
        - Characters
      responses:
        '200':
          description: lista de personajes
    delete:
      summary: elimina un personaje
      description: eliminar un personaje
      
      tags:
        - Characters
      responses:
        '200':
          description: lista de personajes